---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```
# Welcome to the dev-version of the 

#[library flipscores on CRAN](http://cran.r-project.org/web/packages/flipscores/index.html)


* * *

## Set up

To **install** this github version type (in R):

    #if devtools is not installed yet: 
    # install.packages("devtools") 
    library(devtools)
    install_github("livioivil/flipscores")


* * *

## Some examples

```{r,  message = FALSE}
library(flipscores)

###Binomial

set.seed(1)
x=(rep(0:1,20))
D=data.frame(y=rbinom(40,1,.25+x*.5),x=x,z=rnorm(40),id=rep(1:20,each=2))

mod_par=glm(y~x*z,data=D,family = binomial)
summary(mod_par)
mod_par
mod=flipscores_glm(y~x*z,data=D,family = binomial,score_type = "ortho")
summary(mod)
print(mod)
mod=flipscores_glm(y~x*z,data=D,family = binomial,score_type = "ortho", id=D$id)
summary(mod)

###Poisson

set.seed(2)
y=(sample(1:200,20))
x=(rep(0:1,20))
D=data.frame(y=y, x=rbinom(40,1,.25+x*.5), z=rnorm(40),id=rep(1:20,each=2))

mod_par=glm(y~x*z,data=D, family = poisson)
summary(mod_par)
mod=flipscores_glm(y~x*z, data=D, family = poisson, score_type = "ortho")
summary(mod)
mod=flipscores_glm(y~x*z, data=D, family = poisson, score_type = "ortho", id=D$id)
summary(mod)

###Linear model

set.seed(3)
y=rnorm(40)
x=(rep(0:1,20))
D=data.frame(y=y, x=rbinom(40,1,.25+x*.5), z=rnorm(40),id=rep(1:20,each=2))

mod_par=glm(y~x*z,data=D, family = gaussian)
summary(mod_par)
mod=flipscores_glm(y~x*z, data=D, family = gaussian, score_type = "ortho")
summary(mod)
mod=flipscores_glm(y~x*z, data=D, family = gaussian, score_type = "ortho", id=D$id)
summary(mod)

###Gamma

set.seed(4)
y=rgamma(40, shape=9, scale = 0.5)
x=(rep(0:1,20))
D=data.frame(y=y, x=rbinom(40,1,.25+x*.5), z=rnorm(40), x2=rpois(40, lambda = 4) ,id=rep(1:20,each=2))

mod_par=glm(y~x*z+x2,data=D, family = Gamma)
summary(mod_par)
mod=flipscores_glm(y~x*z+x2, data=D, family = Gamma, score_type = "ortho") #> senza +x2 non va?
summary(mod)
mod=flipscores_glm(y~x*z+x2, data=D, family = Gamma, score_type = "ortho", id=D$id)
summary(mod)

```


* * *

## References


## Bug reports
If you encounter a bug, please file a
[reprex](https://github.com/tidyverse/reprex) (minimal reproducible example)
on [github](https://github.com/livioivil/flipscores/issues).
